apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: andriklas/kub-demo-tasks:latest
          env:
          - name: DATA_PATH
            value: "tasks/tasks.txt"
